name: Terraform Apply

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

# env:
#   ROLE_TO_ASSUME: arn:aws:iam::958933161565:role/github-role
#   AWS_REGION: ap-northeast-1

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          # role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          # aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::958933161565:role/github-role
          aws-region: ap-northeast-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: infra/terraform

      - run: terraform apply -auto-approve -input=false
        working-directory: infra/terraform
