name: Terraform Apply

on:
  push:
    branches: [ "main" ]
    paths: infra/terraform/**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::958933161565:role/github-role
          aws-region: ap-northeast-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: infra/terraform

      - run: terraform apply -auto-approve -input=false
        working-directory: infra/terraform
